### ISSUE TITLE
API not working anymore

### ISSUE THREAD

**Issue by collinpowell** [bensonarafat/nga-locality#2]
What happened to the API?

**Comment by bensonarafat** [comment]
@collinpowell 
Thanks for the issue and for using this API. 

I noted why the API is not working on the README  

**_If you currently trying to access this API but not going. This is because i just hit a limit on render and i need to subscribe to their plan. It's not of me to ask but I can't do anything right now. You could read my post and support the API so I can go back online here -> https://buymeacoffee.com/bensonarafat/help-nigeria-state-local-api Thanks, Ben._**

**Comment by bensonarafat** [comment]
@collinpowell 
This is been resolved. 
Thanks
